### PR TITLE
Use GITHUB_WORKSPACE, examine exit code

### PR DESCRIPTION
**Pull request by nkirsch**
Incorporated `xargs`

### CODE REVIEW

**Comment by nkirsch** [comment]
@tqorange looks like it is properly failing now

**Comment by tqorange** [comment]
> @tqorange looks like it is properly failing now

Isn't the yaml in the test directory valid?

**Comment by nkirsch** [comment]
Doesn’t appear to be to kubeyaml

**Comment by tqorange** [comment]
> Doesn’t appear to be to kubeyaml
> […](#)
> On Mar 6, 2020, at 10:48, TQ Berg ***@***.***> wrote: ﻿ @tqorange looks like it is properly failing now Isn't the yaml in the test directory valid? — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

But this works: https://github.com/atsu/k8slynter/blob/master/test.yaml (note _not_ in the test directory)

**Comment by tqorange** [comment]
The 2nd Running is likely wrong:
```
running find yaml on DIR test
sh -c cat $@ | /kubeyaml ; test/test.yaml
running find yml on DIR test
sh -c cat $@ | /kubeyaml ;
```

**Pull request merged**
